[platformio]
default_envs = viewe_uedx48480040e_wb_a

[env:viewe_uedx48480040e_wb_a]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.37/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_upload.flash_size = 16MB
board_build.flash_mode = qio
board_build.f_flash = 80000000L
board_build.arduino.memory_type = qio_opi
board_build.partitions = partitions.csv
custom_sdkconfig =
  CONFIG_SPIRAM_XIP_FROM_PSRAM=y
  CONFIG_SPIRAM_FETCH_INSTRUCTIONS=y
  CONFIG_SPIRAM_RODATA=y
  '# CONFIG_ESP32S3_DATA_CACHE_LINE_32B is not set'
  CONFIG_ESP32S3_DATA_CACHE_LINE_64B=y
  CONFIG_LCD_RGB_ISR_IRAM_SAFE=y
  CONFIG_GDMA_CTRL_FUNC_IN_IRAM=y
  CONFIG_GDMA_ISR_IRAM_SAFE=y
  '# CONFIG_LCD_RGB_RESTART_IN_VSYNC is not set'
  '# CONFIG_BT_NIMBLE_MEM_ALLOC_MODE_INTERNAL is not set'
  CONFIG_BT_NIMBLE_MEM_ALLOC_MODE_EXTERNAL=y
  CONFIG_BT_NIMBLE_HOST_TASK_STACK_SIZE=3584
  CONFIG_BT_NIMBLE_MAX_CONNECTIONS=2
  CONFIG_BT_NIMBLE_MAX_BONDS=1
  CONFIG_BT_NIMBLE_MAX_CCCDS=2
  '# CONFIG_BT_NIMBLE_ROLE_CENTRAL is not set'
  CONFIG_BT_NIMBLE_ROLE_PERIPHERAL=y
  CONFIG_BT_NIMBLE_ROLE_BROADCASTER=y
  '# CONFIG_BT_NIMBLE_ROLE_OBSERVER is not set'
  '# CONFIG_BT_NIMBLE_GATT_CLIENT is not set'
  CONFIG_BT_NIMBLE_GATT_SERVER=y
  CONFIG_BT_NIMBLE_GATT_MAX_PROCS=2
  '# CONFIG_BT_NIMBLE_SM_SC is not set'
  '# CONFIG_BT_NIMBLE_ENABLE_CONN_REATTEMPT is not set'
  '# CONFIG_BT_NIMBLE_50_FEATURE_SUPPORT is not set'
  '# CONFIG_BT_NIMBLE_SECURITY_ENABLE is not set'
  CONFIG_BT_NIMBLE_MSYS_1_BLOCK_COUNT=6
  CONFIG_BT_NIMBLE_MSYS_2_BLOCK_COUNT=12
  CONFIG_BT_NIMBLE_TRANSPORT_EVT_COUNT=15
  CONFIG_BT_NIMBLE_ATT_MAX_PREP_ENTRIES=4
  CONFIG_BT_CTRL_BLE_MAX_ACT=3
build_flags =
  -D BOARD_HAS_PSRAM
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D ESP_PANEL_BOARD_DEFAULT_USE_SUPPORTED=0
  -D ESP_PANEL_BOARD_DEFAULT_USE_CUSTOM=1
  -D ESP_PANEL_BOARD_USE_CUSTOM_FILE=1
  -D ESP_PANEL_BOARD_CUSTOM_FILE_PATH=azoria_viewe_board_conf.h
  -D ESP_PANEL_DRIVERS_BUS_USE_I2C=1
  -I include
  -D LV_CONF_SKIP
  -D LV_COLOR_DEPTH=16
  -D LV_COLOR_16_SWAP=0
  -D LV_USE_FONT_COMPRESSED=1
  -D LV_FONT_MONTSERRAT_18=1
  -D LV_FONT_MONTSERRAT_16=1
  -D LV_FONT_MONTSERRAT_22=1
  -D LV_FONT_MONTSERRAT_28=1
  -D LV_FONT_MONTSERRAT_36=1
  -D LV_FONT_MONTSERRAT_48=1
  -D AZORIA_RGB_CLOCK_HZ=16000000
  -D AZORIA_RGB_BOUNCE_BUFFER_SIZE=28800
lib_deps =
  https://github.com/esp-arduino-libs/ESP32_Display_Panel.git#v1.0.4
  https://github.com/esp-arduino-libs/ESP32_IO_Expander.git#v1.1.0
  https://github.com/esp-arduino-libs/esp-lib-utils.git#v0.2.0
  lvgl/lvgl@8.4.0
lib_ignore =
  DSP
  SPIFFS
  Matter
  Zigbee
  ESP RainMaker
custom_component_remove =
  espressif/esp_hosted
  espressif/esp_wifi_remote
  espressif/network_provisioning
  espressif/esp-dsp
  espressif/esp_modem
  espressif/esp32-camera
  espressif/libsodium
  espressif/esp-modbus
  espressif/qrcode
  espressif/esp_insights
  espressif/esp_diag_data_store
  espressif/esp_diagnostics
  espressif/cbor
  espressif/esp_rainmaker
  espressif/rmaker_common
  chmorgan/esp-libhelix-mp3
